[build]
  command = "npm run build"
  publish = ".next"

# Правила маршрутизации для Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Перенаправляем на статический HTML-файл для обновления программы
[[redirects]]
  from = "/update-kettlebell.html"
  to = "/update-kettlebell.html"
  status = 200
  force = true

# Правило для обработки API-запросов
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Обработка ошибки 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 